# Generated by Django 5.0.6 on 2025-04-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="decription", new_name="description",
        ),
    ]
